import { Inter } from 'next/font/google'
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

const inter = Inter({ subsets: ['latin'] })
config.autoAddCss = false;

export const metadata = {
  title: 'Nabil Saragih',
  description: 'Generated by create next app',
  icons: [
    {
      url: "/images/favicon.png",
    },
  ],
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
